### ISSUE TITLE
bug: change-oauth-client-id patch returns permission access error on Android 10

### ISSUE THREAD

**Issue by rarproj** [ReVanced/revanced-patches-template#2546]
### Type

Error while patching

### Bug description

Returns the following error:
`Failed to apply change-oauth-client-id: /storage/emulated/0/reddit_client_id_revanced.txt: open failed: EACCES (Permission denied)`

Storage permissions are allowed for Revanced Managed (latest version with fresh install).

### Steps to reproduce

Try to apply change-oauth-client-id patch on Android 10

### Relevant log output

```shell
Failed to apply change-oauth-client-id: /storage/emulated/0/reddit_client_id_revanced.txt: open failed: EACCES (Permission denied)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by 40ZqTYY4ag3tAO4hdlxR1** [comment]
Running in to the same issue ... Android 10 and below are not edge cases :)

**Comment by kpietraszko** [comment]
Make sure the manager is updated. Force quit the manager. In android settings for the manager, disable and then enable storage permission. Then try patching again.

**Comment by rarproj** [comment]
Done. Unfortunately still getting the error.

**Comment by rarproj** [comment]
Did not mean to close. I misclicked with the mobile web UI.

**Comment by aliekiddo** [comment]
> Make sure the manager is updated. Force quit the manager. In android settings for the manager, disable and then enable storage permission. Then try patching again.

This (thankfully) worked for me

**Comment by oSumAtrIX** [comment]
This is not a patch issue, move to ReVanced Manager

**Comment by rarproj** [comment]
If this error also happens in the CLI, is it still a Manager issue? If so then I will move over there.

**Comment by aliekiddo** [comment]
I still have a problem with CLI, although I've never used it before so maybe I'm doing something wrong:

`[builder] INFO: Reading dex files
[builder] INFO: Decoding AndroidManifest.xml only, because resources are not needed
[builder] INFO: Skipping change-package-name: Manually excluded
[builder] INFO: Skipping enable-android-debugging: Manually excluded
[builder] INFO: Skipping export-all-activities: Manually excluded
[builder] INFO: Skipping predictive-back-gesture: Manually excluded
[builder] INFO: Skipping remove-screen-capture-restriction: Manually excluded
[builder] INFO: Skipping remove-screenshot-restriction: Manually excluded
[builder] INFO: Skipping spoof-wifi-connection: Manually excluded
[builder] INFO: Executing patches
**[builder] SEVERE: change-oauth-client-id failed:**
[builder] app.revanced.patcher.patch.PatchResultError: No client ID provided at app.revanced.patches.reddit.customclients.AbstractChangeOAuthClientIdPatch.execute(AbstractChangeOAuthClientIdPatch.kt:22) at app.revanced.patches.reddit.customclients.AbstractChangeOAuthClientIdPatch.execute(AbstractChangeOAuthClientIdPatch.kt:11) at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:333) at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38) at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7)`

**Comment by oSumAtrIX** [comment]
You haven't provided a client id as the logs tell you too. Offtopic though
